version: "3.1"
name: king-of-the-hill
services:
  web:
    image: ozyviking/twitch-king-of-the-hill:stable
    ports:
      - 28080:80
    # volumes:
    #   - ./website:/usr/share/nginx/html
    restart: always
  # db:
  #   image: redis
