style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/Ozy-Viking/twitch_king_of_the_hill
options:
  tag_filter_pattern: '^v'
  sort: "semver"
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - refactor
        - weapon
        - test
        - note
  commit_groups:
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      weapon: Weapon Changes
      test: Testing Changes
      note: Notes

  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject

  notes:
    keywords:
      - BREAKING CHANGE
      - note